= LocoSpeed for Arduino =

This is a project to measure the speed of a modell train
You need an Arduino Nano Board, one OLED I2C display and two light barriers

For more information about this project, watch this video:
https://youtu.be/Ywsuv9l1PBs
https://www.youtube.com/MarkusNTrains


== License ==

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
